import React from "react";
import "./About.css";

const About = () => {
  return (
    <div className="grid grid-cols-6 gap-10 w-[60%] min-h-full text-xl font-bold font-serif">
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>

      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>

      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
      <h1>About</h1>
    </div>
  );
};

export default About;
